In [1]:
import numpy as np

In [2]:
a = [1, 2, 3]

In [3]:
arr = np.array(a)

In [4]:
arr

array([1, 2, 3])

In [5]:
a = (1, 2, 3)
arr1 = np.array(a)

In [6]:
arr1

array([1, 2, 3])

In [7]:
arr = np.array([6, 7, np.nan, 9, 10])
arr

array([ 6.,  7., nan,  9., 10.])

In [8]:
arr = arr[~np.isnan(arr)]

In [9]:
arr

array([ 6.,  7.,  9., 10.])

In [10]:
mean = np.nanmean(arr)

In [11]:
mean

np.float64(8.0)

In [12]:
# x = 6, 7, nan, 9, 10  -- 1,000,000 - 20% -- 800,000
# y - independent varirable
# x - dependent variable
# x - attribute, column, features

In [13]:
arr = np.array([6, 7, np.nan, 9, 10])
arr

array([ 6.,  7., nan,  9., 10.])

In [14]:
arr = np.nan_to_num(arr, nan = mean)
arr

array([ 6.,  7.,  8.,  9., 10.])

In [15]:
# pandas - library - structured data

In [16]:
import pandas as pd

In [17]:
d = [1, 2, 3, 4, 5]
d

[1, 2, 3, 4, 5]

In [18]:
e = (1, 2, 3, 4, 5)
e

(1, 2, 3, 4, 5)

In [19]:
df = pd.Series(d)

In [20]:
df

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [21]:
df = pd.Series(e)

In [22]:
df

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [24]:
dic = {'a': 1, 'b': 2, 'c':3}
df = pd.Series(dic)
df

a    1
b    2
c    3
dtype: int64

In [25]:
a = ['a', 'b', 'c']
b = [10, 20, 30]
df = pd.Series(b)
df 

0    10
1    20
2    30
dtype: int64

In [26]:
df = pd.Series(b, index = a)

In [27]:
df

a    10
b    20
c    30
dtype: int64

In [28]:
d = {'id': ['a', 'b', 'c'], 'mark': [100, 90, 80], 'name': ['Damien', 'stefan','Elena']}
df = pd.Series(d)
df

id                    [a, b, c]
mark              [100, 90, 80]
name    [Damien, stefan, Elena]
dtype: object

In [29]:
df = pd.DataFrame(d)
df

,id,mark,name
0,a,100,Damien
1,b,90,stefan
2,c,80,Elena


In [30]:
# when the data is very small to process - pandas

In [31]:
# decorators
# it takes another function as it input
# it adds an extra behaviour to existing function
# it returns new function

In [32]:
def addition(a, b):
    return a + b

In [33]:
addition(10, 20)

30

In [34]:
def my_decorator(func):
    print(f"Before add function")
    def add():
        print(f"Inside add method/function")
        func()
        print(f"After func call")
    return add
    print(f"End of decorator fucntion")

In [35]:
@my_decorator
def trigger_this():
    print(f"I am inside trigger method")

Before add function


In [36]:
trigger_this()

Inside add method/function
I am inside trigger method
After func call


In [37]:
def my_decorator(func):
    print(f"before add function")
    def add_num(*args, **kwargs):
        print(f"IPnside add method/fucntion")
        return func(*args, **kwargs)
        print(f"After func call")
    return add_num
    print(f"end of decorator")

In [38]:
@my_decorator
def trigger_this(p_return):
    print(f"{p_return}")

before add function


In [39]:
trigger_this("Trigger this method")

IPnside add method/fucntion
Trigger this method


In [40]:
def first_function():
    print("Inside first fucntion")
    def second_function():
        print("INside second funtion")

In [41]:
second_function()

NameError: name 'second_function' is not defined

In [44]:
def add_num(*args):
    print(args, type(args))

In [45]:
add_num(1)

(1,) <class 'tuple'>


In [46]:
add_num('a')

('a',) <class 'tuple'>


In [47]:
add_num('a', 'b')

('a', 'b') <class 'tuple'>


In [48]:
add_num('a', 'b', 'c', 'd')

('a', 'b', 'c', 'd') <class 'tuple'>


In [50]:
def check_multiply(*args):
    result = 1
    for i in args:
        result *= i # result = result * i
    return result

In [51]:
print(check_multiply(2, 3, 4))

24


In [ ]:
# kargs - keyword arguments, keys will be its argument name 
# * args - positional args
# **kwargs - keyword args

In [ ]:
'''
tuple                  dict
Yes                     NO
Indexing method         specify the key pari '''

In [53]:
def define_kwargs(**kwargs):
    print(kwargs, type(kwargs))

In [55]:
define_kwargs(first_argument = 'Welcome', second_argument = 'Home')

{'first_argument': 'Welcome', 'second_argument': 'Home'} <class 'dict'>


In [56]:
def args_kwargs(*args, **kwargs):
    print(f"My args are {args}")
    print(f"My kwargs are {kwargs}")

In [57]:
args_kwargs(111, 222, first_argument = 'Welcome', second_argument = 'Home')

My args are (111, 222)
My kwargs are {'first_argument': 'Welcome', 'second_argument': 'Home'}


In [59]:
args_kwargs(11, 222)

My args are (11, 222)
My kwargs are {}


In [63]:
def args_kwargs(*args, **kwargs):
    print(f"My args are {args}")
    print(f"My kargs are {kwargs}")
    print(args[0])
    print(kwargs['second_argument'])

In [64]:
args_kwargs(111, 222, 333, first_argument = 'Welcome', second_argument = 'Home')

My args are (111, 222, 333)
My kargs are {'first_argument': 'Welcome', 'second_argument': 'Home'}
111
Home
